# Import Data and Library

### import necessary library

In [2]:
import kaggle
import pandas as pd
import matplotlib as plt

### Import data from kaggle

In [2]:
kaggle.api.authenticate()
kaggle.api.dataset_download_files('usdot/flight-delays', path='Dataset', unzip=True)

Dataset URL: https://www.kaggle.com/datasets/usdot/flight-delays

In [4]:
pd.read_csv('Dataset/airlines.csv')

   IATA_CODE                       AIRLINE
0         UA         United Air Lines Inc.
1         AA        American Airlines Inc.
2         US               US Airways Inc.
3         F9        Frontier Airlines Inc.
4         B6               JetBlue Airways
5         OO         Skywest Airlines Inc.
6         AS          Alaska Airlines Inc.
7         NK              Spirit Air Lines
8         WN        Southwest Airlines Co.
9         DL          Delta Air Lines Inc.
10        EV   Atlantic Southeast Airlines
11        HA        Hawaiian Airlines Inc.
12        MQ  American Eagle Airlines Inc.
13        VX                Virgin America

In [5]:
pd.read_csv('Dataset/airports.csv')

,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,ABE,Lehigh Valley International Airport,Allentown,PA,USA,40.65236,-75.44040
1,ABI,Abilene Regional Airport,Abilene,TX,USA,32.41132,-99.68190
2,ABQ,Albuquerque International Sunport,Albuquerque,NM,USA,35.04022,-106.60919
3,ABR,Aberdeen Regional Airport,Aberdeen,SD,USA,45.44906,-98.42183
4,ABY,Southwest Georgia Regional Airport,Albany,GA,USA,31.53552,-84.19447
...,...,...,...,...,...,...,...
317,WRG,Wrangell Airport,Wrangell,AK,USA,56.48433,-132.36982
318,WYS,Westerly State Airport,West Yellowstone,MT,USA,44.68840,-111.11764
319,XNA,Northwest Arkansas Regional Airport,Fayetteville/Springdale/Rogers,AR,USA,36.28187,-94.30681
320,YAK,Yakutat Airport,Yakutat,AK,USA,59.50336,-139.66023
321,YUM,Yuma International Airport,Yuma,AZ,USA,32.65658,-114.60597

In [14]:
pd.options.display.max_columns = None
pd.read_csv('Dataset/flights.csv').head(40)

C:\Users\guy88\AppData\Local\Temp\ipykernel_7712\718061863.py:2: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('Dataset/flights.csv').head(40)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,SCHEDULED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,WHEELS_ON,TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,2354.0,-11.0,21.0,15.0,205.0,194.0,169.0,1448,404.0,4.0,430,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,2.0,-8.0,12.0,14.0,280.0,279.0,263.0,2330,737.0,4.0,750,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,18.0,-2.0,16.0,34.0,286.0,293.0,266.0,2296,800.0,11.0,806,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,15.0,-5.0,15.0,30.0,285.0,281.0,258.0,2342,748.0,8.0,805,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,24.0,-1.0,11.0,35.0,235.0,215.0,199.0,1448,254.0,5.0,320,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5,2015,1,1,4,DL,806,N3730B,SFO,MSP,25,20.0,-5.0,18.0,38.0,217.0,230.0,206.0,1589,604.0,6.0,602,610.0,8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
6,2015,1,1,4,NK,612,N635NK,LAS,MSP,25,19.0,-6.0,11.0,30.0,181.0,170.0,154.0,1299,504.0,5.0,526,509.0,-17.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
7,2015,1,1,4,US,2013,N584UW,LAX,CLT,30,44.0,14.0,13.0,57.0,273.0,249.0,228.0,2125,745.0,8.0,803,753.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,1,1,4,AA,1112,N3LAAA,SFO,DFW,30,19.0,-11.0,17.0,36.0,195.0,193.0,173.0,1464,529.0,3.0,545,532.0,-13.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
9,2015,1,1,4,DL,1173,N826DN,LAS,ATL,30,33.0,3.0,12.0,45.0,221.0,203.0,186.0,1747,651.0,5.0,711,656.0,-15.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,2015,1,1,4,DL,2336,N958DN,DEN,ATL,30,24.0,-6.0,12.0,36.0,173.0,149.0,133.0,1199,449.0,4.0,523,453.0,-30.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
11,2015,1,1,4,AA,1674,N853AA,LAS,MIA,35,27.0,-8.0,21.0,48.0,268.0,266.0,238.0,2174,746.0,7.0,803,753.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
12,2015,1,1,4,DL,1434,N547US,LAX,MSP,35,35.0,0.0,18.0,53.0,214.0,210.0,188.0,1535,601.0,4.0,609,605.0,-4.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
13,2015,1,1,4,DL,2324,N3751B,SLC,ATL,40,34.0,-6.0,18.0,52.0,215.0,199.0,176.0,1590,548.0,5.0,615,553.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
14,2015,1,1,4,DL,2440,N651DL,SEA,MSP,40,39.0,-1.0,28.0,107.0,189.0,198.0,166.0,1399,553.0,4.0,549,557.0,8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,2015,1,1,4,AS,108,N309AS,ANC,SEA,45,41.0,-4.0,17.0,58.0,204.0,194.0,173.0,1448,451.0,4.0,509,455.0,-14.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
16,2015,1,1,4,DL,1560,N3743H,ANC,SEA,45,31.0,-14.0,25.0,56.0,210.0,200.0,171.0,1448,447.0,4.0,515,451.0,-24.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
17,2015,1,1,4,UA,1197,N78448,SFO,IAH,48,42.0,-6.0,11.0,53.0,218.0,217.0,199.0,1635,612.0,7.0,626,619.0,-7.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,2015,1,1,4,AS,122,N413AS,ANC,PDX,50,46.0,-4.0,11.0,57.0,215.0,201.0,187.0,1542,504.0,3.0,525,507.0,-18.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
19,2015,1,1,4,DL,1670,N806DN,PDX,MSP,50,45.0,-5.0,9.0,54.0,193.0,186.0,171.0,1426,545.0,6.0,603,551.0,-12.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
20,2015,1,1,4,NK,520,N525NK,LAS,MCI,55,120.0,25.0,11.0,131.0,162.0,143.0,128.0,1139,539.0,4.0,537,543.0,6.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,2015,1,1,4,AA,371,N3GXAA,SEA,MIA,100,52.0,-8.0,30.0,122.0,338.0,347.0,311.0,2724,933.0,6.0,938,939.0,1.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
22,2015,1,1,4,NK,214,N632NK,LAS,DFW,103,102.0,-1.0,13.0,115.0,147.0,147.0,128.0,1055,523.0,6.0,530,529.0,-1.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
23,2015,1,1,4,AA,115,N3CTAA,LAX,MIA,105,103.0,-2.0,14.0,117.0,286.0,276.0,255.0,2342,832.0,7.0,851,839.0,-12.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
24,2015,1,1,4,DL,1450,N671DN,LAS,MSP,105,102.0,-3.0,11.0,113.0,183.0,163.0,150.0,1299,543.0,2.0,608,545.0,-23.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
25,2015,1,1,4,UA,1545,N76517,LAX,IAH,115,112.0,-3.0,11.0,123.0,183.0,175.0,156.0,1379,559.0,8.0,618,607.0,-11.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26,2015,1,1,4,AS,130,N457AS,FAI,SEA,115,107.0,-8.0,25.0,132.0,213.0,218.0,186.0,1533,538.0,7.0,548,545.0,-3.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
27,2015,1,1,4,NK,597,N528NK,MSP,FLL,115,127.0,12.0,14.0,141.0,207.0,220.0,166.0,1487,527.0,40.0,542,607.0,25.0,0,0,NaN,25.0,0.0,0.0,0.0,0.0
28,2015,1,1,4,US,413,N571UW,LAS,CLT,120,110.0,-10.0,12.0,122.0,245.0,224.0,205.0,1916,747.0,7.0,825,754.0,-31.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
29,2015,1,1,4,AA,2392,N3HRAA,DEN,MIA,120,141.0,21.0,12.0,153.0,227.0,208.0,188.0,1709,701.0,8.0,707,709.0,2.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
30,2015,1,1,4,NK,168,N629NK,PHX,ORD,125,237.0,72.0,9.0,246.0,204.0,175.0,156.0,1440,622.0,10.0,549,632.0,43.0,0,0,NaN,43.0,0.0,0.0,0.0,0.0
31,2015,1,1,4,AA,2211,N3CGAA,PHX,MIA,127,116.0,-11.0,10.0,126.0,239.0,234.0,217.0,1972,703.0,7.0,726,710.0,-16.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
32,2015,1,1,4,AS,136,N431AS,ANC,SEA,135,NaN,NaN,NaN,NaN,205.0,NaN,NaN,1448,NaN,NaN,600,NaN,NaN,0,1,A,NaN,NaN,NaN,NaN,NaN
33,2015,1,1,4,DL,95,N320US,SLC,ATL,140,134.0,-6.0,43.0,217.0,215.0,231.0,182.0,1590,719.0,6.0,715,725.0,10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
34,2015,1,1,4,NK,298,N514NK,LAS,IAH,144,140.0,-4.0,10.0,150.0,170.0,170.0,148.0,1222,618.0,12.0,634,630.0,-4.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
35,2015,1,1,4,HA,17,N389HA,LAS,HNL,145,145.0,0.0,16.0,201.0,370.0,385.0,361.0,2762,602.0,8.0,555,610.0,15.0,0,0,NaN,0.0,0.0,15.0,0.0,0.0
36,2015,1,1,4,US,617,N804AW,ANC,PHX,152,143.0,-9.0,21.0,204.0,323.0,322.0,298.0,2552,902.0,3.0,915,905.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
37,2015,1,1,4,UA,1528,N76519,SJU,EWR,154,157.0,3.0,12.0,209.0,255.0,241.0,220.0,1608,449.0,9.0,509,458.0,-11.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
38,2015,1,1,4,AS,134,N464AS,ANC,SEA,155,140.0,-15.0,17.0,157.0,218.0,198.0,170.0,1448,547.0,11.0,633,558.0,-35.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
39,2015,1,1,4,B6,304,N607JB,SJU,JFK,155,153.0,-2.0,12.0,205.0,235.0,248.0,231.0,1598,456.0,5.0,450,501.0,11.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

### Column details
**YEAR** = Year of the Flight Trip <br>
**MONTH** = Month of the Flight Trip <br>
**DAY** = Day of the Flight Trip <br>
**DAY_OF_WEEK** = Day of week of the Flight Trip <br>
**AIRLINE** = Airline Identifier <br>
**FLIGHT_NUMBER** = Flight Identifier <br>
**TAIL_NUMBER** = Aircraft Identifier <br>
**ORIGIN_AIRPORT** = Starting Airport <br>
**DESTINATION_AIRPORT** = Destination Airport <br>
**SCHEDULED_DEPARTURE** = Planned Departure Time <br>
**DEPARTURE_TIME** = WHEEL_OFF - TAXI_OUT <br>
**DEPARTURE_DELAY** = Total Delay on Departure <br>
**TAXI_OUT** = The time duration elapsed between departure from the origin airport gate and wheels off <br>
**WHEELS_OFF** = The time point that the aircraft's wheels leave the ground
**SCHEDULED_TIME** = Planned time amount needed for the flight trip <br>
**ELAPSED_TIME** = AIR_TIME+TAXI_IN+TAXI_OUT <br>
**AIR_TIME** = The time duration between wheels_off and wheels_on time <br>
**DISTANCE** = Distance between two airports <br>
**WHEELS_ON** = The time point that the aircraft's wheels touch on the ground <br>
**TAXI_IN** = The time duration elapsed between wheels-on and gate arrival at the destination airport <br>
**SCHEDULED_ARRIVAL** = Planned arrival time <br>
**ARRIVAL_TIME** = WHEELS_ON+TAXI_IN <br>
**ARRIVAL_DELAY** = ARRIVAL_TIME-SCHEDULED_ARRIVAL <br>
**DIVERTED** = Aircraft landed on airport that out of schedule <br>
**CANCELLED** = Flight Cancelled (1 = cancelled) <br>
**CANCELLATION_REASON** = Reason for Cancellation of flight: A - Airline/Carrier, B - Weather, C - National Air System, D - Security <br>
**AIR_SYSTEM_DELAY** = Delay caused by air system <br>
**SECURITY_DELAY** = Delay caused by security <br>
**AIRLINE_DELAY** = Delay caused by the airline <br>
**LATE_AIRCRAFT_DELAY** = Delay caused by aircraft <br>
**WEATHER_DELAY** = Delay caused by weather <br>

# Clean Data

In [ ]:
# change time format from int to str
df_flights = pd.read_csv('Dataset/flights.csv', dtype={'DEPARTURE_TIME' : str, 'WHEELS_OFF' : str, 'WHEELS_ON' : str, 'SCHEDULED_ARRIVAAL' : str, 'ARRIVAL_TIME' : str })
print(df_flights.head())

C:\Users\guy88\AppData\Local\Temp\ipykernel_7712\1904376590.py:2: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df_flights = pd.read_csv('Dataset/flights.csv', dtype={'DEPARTURE_TIME' : str, 'WHEELS_OFF' : str, 'WHEELS_ON' : str, 'SCHEDULED_ARRIVAAL' : str, 'ARRIVAL_TIME' : str })

   YEAR  MONTH  DAY  DAY_OF_WEEK AIRLINE  FLIGHT_NUMBER TAIL_NUMBER  \
0  2015      1    1            4      AS             98      N407AS
1  2015      1    1            4      AA           2336      N3KUAA
2  2015      1    1            4      US            840      N171US
3  2015      1    1            4      AA            258      N3HYAA
4  2015      1    1            4      AS            135      N527AS

  ORIGIN_AIRPORT DESTINATION_AIRPORT  SCHEDULED_DEPARTURE DEPARTURE_TIME  \
0            ANC                 SEA                    5           2354
1            LAX                 PBI                   10           0002
2            SFO                 CLT                   20           0018
3            LAX                 MIA                   20           0015
4            SEA                 ANC                   25           0024

   DEPARTURE_DELAY  TAXI_OUT WHEELS_OFF  SCHEDULED_TIME  ELAPSED_TIME  \
0            -11.0      21.0       0015           205.0         194.0
1             -8.0      12.0       0014           280.0         279.0
2             -2.0      16.0       0034           286.0         293.0
3             -5.0      15.0       0030           285.0         281.0
4             -1.0      11.0       0035           235.0         215.0

   AIR_TIME  DISTANCE WHEELS_ON  TAXI_IN  SCHEDULED_ARRIVAL ARRIVAL_TIME  \
0     169.0      1448      0404      4.0                430         0408
1     263.0      2330      0737      4.0                750         0741
2     266.0      2296      0800     11.0                806         0811
3     258.0      2342      0748      8.0                805         0756
4     199.0      1448      0254      5.0                320         0259

   ARRIVAL_DELAY  DIVERTED  CANCELLED CANCELLATION_REASON  AIR_SYSTEM_DELAY  \
0          -22.0         0          0                 NaN               NaN
1           -9.0         0          0                 NaN               NaN
2            5.0         0          0                 NaN               NaN
3           -9.0         0          0                 NaN               NaN
4          -21.0         0          0                 NaN               NaN

   SECURITY_DELAY  AIRLINE_DELAY  LATE_AIRCRAFT_DELAY  WEATHER_DELAY
0             NaN            NaN                  NaN            NaN
1             NaN            NaN                  NaN            NaN
2             NaN            NaN                  NaN            NaN
3             NaN            NaN                  NaN            NaN
4             NaN            NaN                  NaN            NaN

In [30]:
# create dataframe for canceled flights
cancelled_flights = df_flights[df_flights['CANCELLED'] == 1].reset_index()
print(cancelled_flights)

         index  YEAR  MONTH  DAY  DAY_OF_WEEK AIRLINE  FLIGHT_NUMBER  \
0           32  2015      1    1            4      AS            136
1           42  2015      1    1            4      AA           2459
2           68  2015      1    1            4      OO           5254
3           82  2015      1    1            4      MQ           2859
4           90  2015      1    1            4      OO           5460
...        ...   ...    ...  ...          ...     ...            ...
89879  5818090  2015     12   31            4      UA           1789
89880  5818157  2015     12   31            4      UA            222
89881  5818318  2015     12   31            4      AA           2245
89882  5818777  2015     12   31            4      NK            416
89883  5818843  2015     12   31            4      AA           1042

      TAIL_NUMBER ORIGIN_AIRPORT DESTINATION_AIRPORT  SCHEDULED_DEPARTURE  \
0          N431AS            ANC                 SEA                  135
1          N3BDAA            PHX                 DFW                  200
2          N746SK            MAF                 IAH                  510
3          N660MQ            SGF                 DFW                  525
4          N583SW            RDD                 SFO                  530
...           ...            ...                 ...                  ...
89879         NaN            IAH                 TPA                 1955
89880         NaN            SFO                 LAX                 2000
89881      N880AA            MIA                 SAN                 2019
89882      N522NK            FLL                 IAG                 2155
89883      N870AA            SAN                 MIA                 2210

      DEPARTURE_TIME  DEPARTURE_DELAY  TAXI_OUT WHEELS_OFF  SCHEDULED_TIME  \
0                NaN              NaN       NaN        NaN           205.0
1                NaN              NaN       NaN        NaN           120.0
2                NaN              NaN       NaN        NaN            87.0
3                NaN              NaN       NaN        NaN            95.0
4                NaN              NaN       NaN        NaN            90.0
...              ...              ...       ...        ...             ...
89879            NaN              NaN       NaN        NaN           125.0
89880            NaN              NaN       NaN        NaN            96.0
89881            NaN              NaN       NaN        NaN           337.0
89882            NaN              NaN       NaN        NaN           175.0
89883            NaN              NaN       NaN        NaN           277.0

       ELAPSED_TIME  AIR_TIME  DISTANCE WHEELS_ON  TAXI_IN  SCHEDULED_ARRIVAL  \
0               NaN       NaN      1448       NaN      NaN                600
1               NaN       NaN       868       NaN      NaN                500
2               NaN       NaN       429       NaN      NaN                637
3               NaN       NaN       364       NaN      NaN                700
4               NaN       NaN       199       NaN      NaN                700
...             ...       ...       ...       ...      ...                ...
89879           NaN       NaN       787       NaN      NaN               2300
89880           NaN       NaN       337       NaN      NaN               2136
89881           NaN       NaN      2267       NaN      NaN               2256
89882           NaN       NaN      1176       NaN      NaN                 50
89883           NaN       NaN      2267       NaN      NaN                547

      ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED CANCELLATION_REASON  \
0              NaN            NaN         0          1                   A
1              NaN            NaN         0          1                   B
2              NaN            NaN         0          1                   B
3              NaN            NaN         0          1                   B
4              NaN            NaN         0          1                   A
...            ...            ...       ...        ...                 ...
89879          NaN            NaN         0          1                   A
89880          NaN            NaN         0          1                   A
89881          NaN            NaN         0          1                   A
89882          NaN            NaN         0          1                   A
89883          NaN            NaN         0          1                   A

       AIR_SYSTEM_DELAY  SECURITY_DELAY  AIRLINE_DELAY  LATE_AIRCRAFT_DELAY  \
0                   NaN             NaN            NaN                  NaN
1                   NaN             NaN            NaN                  NaN
2                   NaN             NaN            NaN                  NaN
3                   NaN             NaN            NaN                  NaN
4                   NaN             NaN            NaN                  NaN
...                 ...             ...            ...                  ...
89879               NaN             NaN            NaN                  NaN
89880               NaN             NaN            NaN                  NaN
89881               NaN             NaN            NaN                  NaN
89882               NaN             NaN            NaN                  NaN
89883               NaN             NaN            NaN                  NaN

       WEATHER_DELAY
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
...              ...
89879            NaN
89880            NaN
89881            NaN
89882            NaN
89883            NaN

[89884 rows x 32 columns]

In [31]:
# create dataframe for diverted flights
diverted_flights = df_flights[df_flights['DIVERTED'] == 1].reset_index()
print(diverted_flights)

         index  YEAR  MONTH  DAY  DAY_OF_WEEK AIRLINE  FLIGHT_NUMBER  \
0          724  2015      1    1            4      DL            716
1         1455  2015      1    1            4      OO           5237
2         2218  2015      1    1            4      WN           1966
3         2526  2015      1    1            4      EV           4555
4         2866  2015      1    1            4      WN           1081
...        ...   ...    ...  ...          ...     ...            ...
15182  5813860  2015     12   31            4      UA           1291
15183  5815052  2015     12   31            4      EV           2785
15184  5816657  2015     12   31            4      UA            291
15185  5817342  2015     12   31            4      MQ           3060
15186  5818160  2015     12   31            4      WN           5296

      TAIL_NUMBER ORIGIN_AIRPORT DESTINATION_AIRPORT  SCHEDULED_DEPARTURE  \
0          N944DL            OMA                 ATL                  645
1          N712SK            MKE                 IAH                  745
2          N685SW            ATL                 JAX                  845
3          N12552            IAH                 HRL                  902
4          N214WN            MDW                 OKC                  930
...           ...            ...                 ...                  ...
15182      N596UA            LIH                 LAX                 1405
15183      N684JW            DFW                 BRO                 1530
15184      N76505            IAD                 SMF                 1735
15185      N648MQ            DFW                 FAR                 1830
15186      N419WN            MDW                 ABQ                 2000

      DEPARTURE_TIME  DEPARTURE_DELAY  TAXI_OUT WHEELS_OFF  SCHEDULED_TIME  \
0               0637             -8.0      27.0       0704           144.0
1               0742             -3.0      15.0       0757           176.0
2               0922             37.0       9.0       0931            75.0
3               0859             -3.0      33.0       0932            75.0
4               0926             -4.0       9.0       0935           125.0
...              ...              ...       ...        ...             ...
15182           1901            296.0       9.0       1910           336.0
15183           1555             25.0      14.0       1609           110.0
15184           1740              5.0       9.0       1749           351.0
15185           1840             10.0      12.0       1852           163.0
15186           2013             13.0      10.0       2023           195.0

       ELAPSED_TIME  AIR_TIME  DISTANCE WHEELS_ON  TAXI_IN  SCHEDULED_ARRIVAL  \
0               NaN       NaN       821      1447      4.0               1009
1               NaN       NaN       984      1456      9.0               1041
2               NaN       NaN       270      1214      5.0               1000
3               NaN       NaN       295      1314      5.0               1017
4               NaN       NaN       691      1340      3.0               1135
...             ...       ...       ...       ...      ...                ...
15182           NaN       NaN      2615       NaN      NaN               2141
15183           NaN       NaN       482       NaN      NaN               1720
15184           NaN       NaN      2358      2212      4.0               2026
15185           NaN       NaN       968      2247      3.0               2113
15186           NaN       NaN      1121      2319      6.0               2215

      ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED CANCELLATION_REASON  \
0             1451            NaN         1          0                 NaN
1             1505            NaN         1          0                 NaN
2             1219            NaN         1          0                 NaN
3             1319            NaN         1          0                 NaN
4             1343            NaN         1          0                 NaN
...            ...            ...       ...        ...                 ...
15182          NaN            NaN         1          0                 NaN
15183          NaN            NaN         1          0                 NaN
15184         2216            NaN         1          0                 NaN
15185         2250            NaN         1          0                 NaN
15186         2325            NaN         1          0                 NaN

       AIR_SYSTEM_DELAY  SECURITY_DELAY  AIRLINE_DELAY  LATE_AIRCRAFT_DELAY  \
0                   NaN             NaN            NaN                  NaN
1                   NaN             NaN            NaN                  NaN
2                   NaN             NaN            NaN                  NaN
3                   NaN             NaN            NaN                  NaN
4                   NaN             NaN            NaN                  NaN
...                 ...             ...            ...                  ...
15182               NaN             NaN            NaN                  NaN
15183               NaN             NaN            NaN                  NaN
15184               NaN             NaN            NaN                  NaN
15185               NaN             NaN            NaN                  NaN
15186               NaN             NaN            NaN                  NaN

       WEATHER_DELAY
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
...              ...
15182            NaN
15183            NaN
15184            NaN
15185            NaN
15186            NaN

[15187 rows x 32 columns]

In [38]:
# create dataframe for delayed flight
delayed_flights = df_flights[
    df_flights['AIR_SYSTEM_DELAY'].notna() & 
    df_flights['SECURITY_DELAY'].notna() & 
    df_flights['AIRLINE_DELAY'].notna() & 
    df_flights['LATE_AIRCRAFT_DELAY'].notna() & 
    df_flights['WEATHER_DELAY'].notna()
].reset_index(drop=True)

print(delayed_flights)

         YEAR  MONTH  DAY  DAY_OF_WEEK AIRLINE  FLIGHT_NUMBER TAIL_NUMBER  \
0        2015      1    1            4      NK            597      N528NK
1        2015      1    1            4      NK            168      N629NK
2        2015      1    1            4      HA             17      N389HA
3        2015      1    1            4      B6           1030      N239JB
4        2015      1    1            4      B6           2134      N307JB
...       ...    ...  ...          ...     ...            ...         ...
1063434  2015     12   31            4      B6           1029      N328JB
1063435  2015     12   31            4      AS             28      N477AS
1063436  2015     12   31            4      NK            371      N661NK
1063437  2015     12   31            4      B6           1248      N948JB
1063438  2015     12   31            4      B6            802      N589JB

        ORIGIN_AIRPORT DESTINATION_AIRPORT  SCHEDULED_DEPARTURE  \
0                  MSP                 FLL                  115
1                  PHX                 ORD                  125
2                  LAS                 HNL                  145
3                  BQN                 MCO                  307
4                  SJU                 MCO                  400
...                ...                 ...                  ...
1063434            MCO                 BQN                 2342
1063435            SEA                 MSP                 2355
1063436            FLL                 BQN                 2358
1063437            LAS                 JFK                 2359
1063438            SLC                 MCO                 2359

        DEPARTURE_TIME  DEPARTURE_DELAY  TAXI_OUT WHEELS_OFF  SCHEDULED_TIME  \
0                 0127             12.0      14.0       0141           207.0
1                 0237             72.0       9.0       0246           204.0
2                 0145              0.0      16.0       0201           370.0
3                 0304             -3.0      25.0       0329           173.0
4                 0535             95.0       9.0       0544           185.0
...                ...              ...       ...        ...             ...
1063434           0003             21.0      10.0       0013           163.0
1063435           0011             16.0      10.0       0021           192.0
1063436           0011             13.0      15.0       0026           140.0
1063437           0238            159.0      34.0       0312           282.0
1063438           0015             16.0      14.0       0029           249.0

         ELAPSED_TIME  AIR_TIME  DISTANCE WHEELS_ON  TAXI_IN  \
0               220.0     166.0      1487      0527     40.0
1               175.0     156.0      1440      0622     10.0
2               385.0     361.0      2762      0602      8.0
3               196.0     160.0      1129      0509     11.0
4               175.0     163.0      1189      0727      3.0
...               ...       ...       ...       ...      ...
1063434         162.0     145.0      1129      0338      7.0
1063435         204.0     189.0      1399      0530      5.0
1063436         155.0     121.0       982      0327     19.0
1063437         282.0     243.0      2248      1015      5.0
1063438         250.0     211.0      1931      0600     25.0

         SCHEDULED_ARRIVAL ARRIVAL_TIME  ARRIVAL_DELAY  DIVERTED  CANCELLED  \
0                      542         0607           25.0         0          0
1                      549         0632           43.0         0          0
2                      555         0610           15.0         0          0
3                      500         0520           20.0         0          0
4                      605         0730           85.0         0          0
...                    ...          ...            ...       ...        ...
1063434                325         0345           20.0         0          0
1063435                507         0535           28.0         0          0
1063436                318         0346           28.0         0          0
1063437                741         1020          159.0         0          0
1063438                608         0625           17.0         0          0

        CANCELLATION_REASON  AIR_SYSTEM_DELAY  SECURITY_DELAY  AIRLINE_DELAY  \
0                       NaN              25.0             0.0            0.0
1                       NaN              43.0             0.0            0.0
2                       NaN               0.0             0.0           15.0
3                       NaN              20.0             0.0            0.0
4                       NaN               0.0             0.0           85.0
...                     ...               ...             ...            ...
1063434                 NaN               0.0             0.0           17.0
1063435                 NaN              12.0             0.0           16.0
1063436                 NaN              15.0             0.0           13.0
1063437                 NaN               0.0             0.0          159.0
1063438                 NaN               1.0             0.0           16.0

         LATE_AIRCRAFT_DELAY  WEATHER_DELAY
0                        0.0            0.0
1                        0.0            0.0
2                        0.0            0.0
3                        0.0            0.0
4                        0.0            0.0
...                      ...            ...
1063434                  3.0            0.0
1063435                  0.0            0.0
1063436                  0.0            0.0
1063437                  0.0            0.0
1063438                  0.0            0.0

[1063439 rows x 31 columns]

# EDA